# Generated by Django 2.1 on 2019-02-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoseite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windenfahrer',
            name='mitglied',
        ),
        migrations.DeleteModel(
            name='Mitglied',
        ),
        migrations.DeleteModel(
            name='Windenfahrer',
        ),
    ]
